const mokemon = {
    "Apismanion": {
        frameCount: {x: 1, y: 1},
        width: .875,
        height: 1,
        walkSpeed: 1,
        runSpeed: 3,
        fleeRadius: 10,
        foodValue: 160,
        hunger: 16,
        max_hp: 10,
        immuneResponse: 1,
        description: "A creature of the swamp. Shy, and faster than it looks. Its legs don't make sense, but it's cute.",
        frequency: {},
    },
    "Dezzy": {
        frameCount: {x: 1, y: 1},
        width: .75,
        height: 1.2,
        walkSpeed: 1,
        runSpeed: 2,
        fleeRadius: 10,
        foodValue: 140,
        hunger: 8,
        max_hp: 9,
        immuneResponse: 2,
        description: "A fun-loving flipper-flopper, hardy and disease resistant. Doesn't eat much.",
        frequency: {},
    },
    "Mallowbear": {
        frameCount: {x: 1, y: 1},
        width: 1,
        height: 1.2,
        walkSpeed: 1,
        runSpeed: 2,
        fleeRadius: 6,
        foodValue: 220,
        hunger: 34,
        max_hp: 20,
        immuneResponse: .3,
        description: "Strong, sturdy, and stoic. Eats a lot. Susceptible to disease.",
        frequency: {},
    },
    "Marlequin": {
        frameCount: {x: 1, y: 1},
        width: .9,
        height: 1.1,
        walkSpeed: 1,
        runSpeed: 3,
        fleeRadius: 10,
        foodValue: 90,
        randomMotion: 3,
        foodValue: 190,
        hunger: 10,
        max_hp: 13,
        immuneResponse: .9,
        description: "Enigmatic and rare. Might have special powers, or maybe it just wants you to think that.",
        frequency: {},
    },
    "Wingmat": {
        frameCount: {x: 1, y: 1},
        width: 1.75,
        height: 1,
        walkSpeed: 1,
        runSpeed: 1.7,
        fleeRadius: 10,
        foodValue: 250,
        hunger: 16,
        max_hp: 10,
        immuneResponse: 1.5,
        description: "Looks like it could maybe fly, but can't. Pretty good to eat in a pinch.",
        frequency: {},
    },
    "Zyant": {
        frameCount: {x: 1, y: 1},
        width: 1.2,
        height: 1.2,
        walkSpeed: 1,
        runSpeed: 3.5,
        fleeRadius: 10,
        foodValue: 220,
        hunger: 14,
        max_hp: 18,
        immuneResponse: 1.8,
        description: "This mysterious deer-thing is found in the woods, lurking behind a tree. Strong, resilient and very quiet.",
        frequency: {},
    },
    "Shadowdragon": {
        frameCount: {x: 1, y: 2},
        width: 2,
        height: 1.75,
        walkSpeed: .75,
        runSpeed: 3,
        chaseRadius: 10,
        attackVerb: "strikes",
        damage: 75,
        foodValue: 350,
        hunger: 50,
        max_hp: 25,
        immuneResponse: 1,
        description: "Part dragon, part dog, part mantis, pretty big, definitely worth a lot of money. Eats a ton.",
        frequency: {},
    },
    "Fragglegod": {
        frameCount: {x: 2, y: 2},
        width: 1.4,
        height: 1.4,
        thumbnailWidth: 0.8,
        walkSpeed: .75,
        runSpeed: 1.5,
        fleeRadius: 10,
        chaseRadius: 5,
        attackRange: 2,
        attackVerb: "smites",
        damage: 100,
        foodValue: 150,
        hunger: 10,
        max_hp: 5,
        immuneResponse: 1,
        description: "Loyal and powerful, but not tough. Bring this one out when you need a pinch hitter.",
        frequency: {},
    }
}
module.exports = mokemon