const mokemon = {
    "Apismanion": {
        frameCount: {x: 1, y: 1},
        width: .875,
        height: 1,
        walkSpeed: 1,
        runSpeed: 2,
        fleeRadius: 10,
        foodValue: 100,
        hp: 10,
    },
    "Dezzy": {
        frameCount: {x: 1, y: 1},
        width: .75,
        height: 1.2,
        walkSpeed: 1,
        runSpeed: 2,
        fleeRadius: 10,
        foodValue: 160,
        hp: 9,
    },
    "Mallowbear": {
        frameCount: {x: 1, y: 1},
        width: 1,
        height: 1.2,
        walkSpeed: 1,
        runSpeed: 2,
        fleeRadius: 6,
        hp: 20,
        foodValue: 200,
    },
    "Marlequin": {
        frameCount: {x: 1, y: 1},
        width: .75,
        height: 1,
        walkSpeed: 1,
        runSpeed: 3,
        fleeRadius: 10,
        foodValue: 90,
        hp: 11,
        randomMotion: 3,
    },
    "Wingmat": {
        frameCount: {x: 1, y: 1},
        width: 1.75,
        height: 1,
        walkSpeed: 1,
        runSpeed: 2,
        fleeRadius: 10,
        foodValue: 210,
        hp: 10,
    },
    "Zyant": {
        frameCount: {x: 1, y: 1},
        width: 1.2,
        height: 1.2,
        walkSpeed: 1,
        runSpeed: 2,
        fleeRadius: 10,
        foodValue: 200,
        hp: 15,
    },
    "Shadowdragon": {
        frameCount: {x: 1, y: 2},
        width: 2,
        height: 1.75,
        walkSpeed: .75,
        runSpeed: 3,
        chaseRadius: 10,
        attackVerb: "strikes",
        damage: 75,
        foodValue: 350,
        hp: 45,
    },
    "Fragglegod": {
        frameCount: {x: 1, y: 1},
        width: 1,
        height: 1.75,
        walkSpeed: .75,
        runSpeed: 1.5,
        fleeRadius: 10,
        chaseRadius: 5,
        attackVerb: "smites",
        damage: 100,
        foodValue: 150,
        hp: 45,
    }
}